name: harmoniq
description: "A flutter mobile app that uses ai to create music in an intuitive way." 

publish_to: 'none' 
version: 1.0.1+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.2.1
  flutter_midi_pro: ^3.1.4
  linked_scroll_controller: ^0.2.0
  firebase_storage: ^12.4.6
  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  http: ^1.4.0
  cloud_firestore: ^5.6.8
  intl: ^0.19.0

  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_logo.png"

flutter:

  uses-material-design: true
  generate: true

  assets:
   - assets/sf2/
   - assets/images/
  
  fonts:
    - family: Poppins
      fonts:
        - asset : assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset : assets/fonts/Poppins-Regular.ttf
