name: harmoniq
description: "A flutter mobile app that uses ai to create music in an intuitive way." 
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.2.1
  flutter_midi_pro: ^3.1.4
  linked_scroll_controller: ^0.2.0
  firebase_storage: ^12.4.6
  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  http: ^1.4.0
  cloud_firestore: ^5.6.8
  intl: ^0.19.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  generate: true

  assets:
   - assets/sf2/alex_gm.sf2
   - assets/images/home_background.png
   - assets/images/login_background.png
   - assets/images/signup_background.png
   - assets/images/main_logo.png
  
  fonts:
    - family: Poppins
      fonts:
        - asset : assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset : assets/fonts/Poppins-Regular.ttf
